services:
  app:
    build: .
    ports:
      - "8000:8000"
      - "6001:6001"
    volumes:
      - .:/var/www
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - DB_HOST=host.docker.internal
      - DB_PORT=3306
      - DB_DATABASE=sneaker-store
      - DB_USERNAME=admin
      - DB_PASSWORD=123456
      - REDIS_HOST=host.docker.internal
      - REDIS_PORT=6379
    extra_hosts:
      - "host.docker.internal:host-gateway"
      
  beanstalkd:
    image: schickling/beanstalkd
    ports:
      - "11300:11300"
  
  beanstalkd-console:
    image: schickling/beanstalkd-console
    ports:
      - "2080:2080"
    depends_on:
      - beanstalkd
